version: '3'

networks:
  pledge-bridge:

services:
  pledge-bridge-relayer0:
    image: chainsafe/chainbridge:v1.1.5
    container_name: relayer0
    restart: always
    environment:
      - KEYSTORE_PASSWORD=pledge
    command: --config /config/config.json --verbosity trace --blockstore /blockstore  --latest
    volumes:
      - ./config/config0.json:/config/config.json
      - ./blockstore:/blockstore
      - ./keys/0x100c8DA1f36e6f097778dA71ea6937bBF9f803fB.key:/keys/0x100c8DA1f36e6f097778dA71ea6937bBF9f803fB.key
    networks:
      - pledge-bridge
  pledge-bridge-relayer1:
    image: chainsafe/chainbridge:v1.1.5
    container_name: relayer1
    restart: always
    environment:
      - KEYSTORE_PASSWORD=pledge
    command: --config /config/config.json --verbosity trace --blockstore /blockstore --latest
    volumes:
      - ./config/config1.json:/config/config.json
      - ./blockstore:/blockstore
      - ./keys/0x4a9b6dd4F7180E30784657fA7e96151AFf71063A.key:/keys/0x4a9b6dd4F7180E30784657fA7e96151AFf71063A.key
    networks:
      - pledge-bridge
  pledge-bridge-relayer2:
    image: chainsafe/chainbridge:v1.1.5
    container_name: relayer2
    restart: always
    environment:
      - KEYSTORE_PASSWORD=pledge
    command: --config /config/config.json --verbosity trace --blockstore /blockstore --latest
    volumes:
      - ./config/config2.json:/config/config.json
      - ./blockstore:/blockstore
      - ./keys/0x1a1285b9c5B32F0ae2a45046571dB53092010169.key:/keys/0x1a1285b9c5B32F0ae2a45046571dB53092010169.key
    networks:
      - pledge-bridge
